<?php

/**
 * Generated by OutlineTestGenerator on 2016-02-01 at 14:52:54.
 */
class FeaturesTest extends TestCase
{

    public function testGet_Sending_a_code_Returns_200()
    {
        $this->get("/code/send?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(200);
    }

    public function testGet_Sending_a_code_Returns_400()
    {
        $this->get("/code/send?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(400);
    }

    public function testGet_Sending_a_code_Returns_406()
    {
        $this->get("/code/send?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(406);
    }

    public function testGet_Sending_a_code_Returns_401()
    {
        $this->get("/code/send?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(401);
    }

    public function testGet_Resending_a_code_Returns_200()
    {
        $this->get("/code/resend?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(200);
    }

    public function testGet_Resending_a_code_Returns_400()
    {
        $this->get("/code/resend?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(400);
    }

    public function testGet_Resending_a_code_Returns_406()
    {
        $this->get("/code/resend?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(406);
    }

    public function testGet_Resending_a_code_Returns_412()
    {
        $this->get("/code/resend?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(412);
    }

    public function testGet_Resending_a_code_Returns_401()
    {
        $this->get("/code/resend?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(401);
    }

    public function testGet_Checking_if_a_user_is_verified_Returns_200()
    {
        $this->get("/user/check?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(200);
    }

    public function testGet_Checking_if_a_user_is_verified_Returns_400()
    {
        $this->get("/user/check?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(400);
    }

    public function testGet_Checking_if_a_user_is_verified_Returns_403()
    {
        $this->get("/user/check?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(403);
    }

    public function testGet_Checking_if_a_user_is_verified_Returns_406()
    {
        $this->get("/user/check?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(406);
    }

    public function testGet_Checking_if_a_user_is_verified_Returns_401()
    {
        $this->get("/user/check?phone_number=27848118111&atlas_user_id=101")
            ->assertResponseStatus(401);
    }

    public function testPut_Verifying_a_user_Returns_200()
    {
        $this->put("/user/verify")
            ->assertResponseStatus(200);
    }

    public function testPut_Verifying_a_user_Returns_400()
    {
        $this->put("/user/verify")
            ->assertResponseStatus(400);
    }

    public function testPut_Verifying_a_user_Returns_406()
    {
        $this->put("/user/verify")
            ->assertResponseStatus(406);
    }

    public function testPut_Verifying_a_user_Returns_404()
    {
        $this->put("/user/verify")
            ->assertResponseStatus(404);
    }

    public function testPut_Verifying_a_user_Returns_401()
    {
        $this->put("/user/verify")
            ->assertResponseStatus(401);
    }

    public function testPut_Blocking_a_user_Returns_200()
    {
        $this->put("/user/block")
            ->assertResponseStatus(200);
    }

    public function testPut_Blocking_a_user_Returns_400()
    {
        $this->put("/user/block")
            ->assertResponseStatus(400);
    }

    public function testPut_Blocking_a_user_Returns_406()
    {
        $this->put("/user/block")
            ->assertResponseStatus(406);
    }

    public function testPut_Blocking_a_user_Returns_404()
    {
        $this->put("/user/block")
            ->assertResponseStatus(404);
    }

    public function testPut_Blocking_a_user_Returns_401()
    {
        $this->put("/user/block")
            ->assertResponseStatus(401);
    }

    public function testGet_Fetching_credits_available_Returns_200()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(200);
    }

    public function testGet_Fetching_credits_available_Returns_402()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(402);
    }

    public function testGet_Fetching_credits_available_Returns_401()
    {
        $this->get("/status/credits")
            ->assertResponseStatus(401);
    }

}
